export const routerString = {
  Forbidden: "/forbidden",
  Unauthorized: "/notfound",
  ServerError: "/servererror",
  login: "/login",
  home: "/home",
  histories: "/histories",
  appointment: "/appointment",
  appointmentDetail: "/appointmentroom/medical/detail",
  appointmentWaitingDetail: "/appointmentroom/medical/waitingdetail",
  schedule: "/schedule",
  manageaccount: "/manageaccount",
  manageaccountdoctor: "/manageaccount/doctor",
  manageaccountuser: "/manageaccount/user",
  accountdetail: "/manageaccount/user/detail",
  doctordetail: "/manageaccount/doctor/detail",
  managedepartments: "/department",
  manageroom: "/room",
  manageappointmentroom: "/room/appointmentroom",
  managetestingroom: "/room/testingroom",
  TestingAppointmentDetail: "/appointmentroom/service/detail",
  manageservice: "/service",
  managemedication: "/medication",
  managepatient: "/managepatient",
  patientdetail: "/managepatient/detail",
  patientdetailByAdmin: "/manageaccount/patient/detail",
  managePatientByAdmin: "/manageaccount/patient",
  requestschedule: "/requestschedule",
  appointmentroom: "/appointmentroom",
  appointmentroom1: "/appointmentroom/medical",
  appointmentroom2: "/appointmentroom/service",
  room: "/room",
  room1: "/room/medical",
  room2: "/room/service",
  chart: "/chart"
}

export const mappingRouter = {
  [routerString.home]: "Tổng quát",
  [routerString.histories]: "Lịch sử khám bệnh",
  [routerString.appointment]: "Khám bệnh",
  [routerString.schedule]: "Lịch hẹn",
  [routerString.manageaccount]: "Quản lý tài khoản",
  [routerString.manageaccountdoctor]: "Bác sĩ",
  [routerString.manageaccountuser]: "Người dùng",
  [routerString.accountdetail]: "Chi tiết người dùng",
  [routerString.doctordetail]: "Chi tiết bác sĩ",
  [routerString.managedepartments]: "Khoa",
  [routerString.manageroom]: "Quản lý phòng khám",
  [routerString.manageappointmentroom]: "Phòng khám bệnh",
  [routerString.managetestingroom]: "Phòng chức năng",
  [routerString.manageservice]: "Dịch vụ",
  [routerString.managemedication]: "Thuốc",
  [routerString.managepatient]: "Danh sách bệnh nhân",
  [routerString.patientdetail]: "Chi tiết bệnh nhân",
  [routerString.patientdetailByAdmin]: "Chi tiết bệnh nhân",
  [routerString.requestschedule]: "Đặt lịch khám bệnh",
  [routerString.managePatientByAdmin]: "Bệnh nhân",
  [routerString.appointmentDetail]: "Chi tiết lịch hẹn",
  [routerString.appointmentWaitingDetail]: "Chi tiết lịch hẹn đang chờ",
  [routerString.appointmentroom]: "Khám bệnh",
  [routerString.appointmentroom1]: "Lịch hẹn",
  [routerString.appointmentroom2]: "Cận lâm sàn",
  [routerString.room]: "Phòng khám",
  [routerString.room1]: "Khám bệnh",
  [routerString.room2]: "Chức năng",
  [routerString.TestingAppointmentDetail]: "Chi tiết kiểm tra cận lâm sàn",
  [routerString.chart]: "Thống kê"
}